//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlQuestion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> HOURS { get; set; }
        public Nullable<decimal> AVG_GRADE { get; set; }
        public Nullable<int> NUM_OF_STUDENTS { get; set; }
        public Nullable<int> HIGHEST_GRADE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
        public override string ToString()
        {
            return $"{this.ID} {this.NAME} {this.HOURS} {this.AVG_GRADE} {this.NUM_OF_STUDENTS} {this.HIGHEST_GRADE}";
        }
    }
}
